

# The amount of different macro actions a player can take. 
protoss_macro_actions = [
    # Buildings
    'BUILD_ASSIMILATOR',
    'BUILD_CYBERNETICSCORE',
    'BUILD_DARKSHRINE',
    'BUILD_FLEETBEACON',
    'BUILD_FORGE',
    'BUILD_GATEWAY',
    'BUILD_INTERCEPTORS',
    'BUILD_NEXUS',
    'BUILD_PHOTONCANNON',
    'BUILD_PYLON',
    'BUILD_ROBOTICSBAY',
    'BUILD_ROBOTICSFACILITY',
    'BUILD_SHIELDBATTERY',
    'BUILD_STARGATE',
    'BUILD_STASISTRAP',
    'BUILD_TEMPLARARCHIVE',
    'BUILD_TWILIGHTCOUNCIL',

    # Morph
    'MORPH_ARCHON',
    'MORPH_GATEWAY',
    'MORPH_MOTHERSHIP',
    'MORPH_WARPGATE',

    # Research
    'RESEARCH_ADEPTRESONATINGGLAIVES',
    'RESEARCH_BLINK',
    'RESEARCH_CHARGE',
    'RESEARCH_EXTENDEDTHERMALLANCE',
    'RESEARCH_GRAVITICBOOSTER',
    'RESEARCH_GRAVITICDRIVE',
    'RESEARCH_INTERCEPTORGRAVITONCATAPULT',
    'RESEARCH_PHOENIXANIONPULSECRYSTALS',
    'RESEARCH_PROTOSSAIRARMOR',
    'RESEARCH_PROTOSSAIRARMORLEVEL1',
    'RESEARCH_PROTOSSAIRARMORLEVEL2',
    'RESEARCH_PROTOSSAIRARMORLEVEL3',
    'RESEARCH_PROTOSSAIRWEAPONS',
    'RESEARCH_PROTOSSAIRWEAPONSLEVEL1',
    'RESEARCH_PROTOSSAIRWEAPONSLEVEL2',
    'RESEARCH_PROTOSSAIRWEAPONSLEVEL3',
    'RESEARCH_PROTOSSGROUNDARMOR',
    'RESEARCH_PROTOSSGROUNDARMORLEVEL1',
    'RESEARCH_PROTOSSGROUNDARMORLEVEL2',
    'RESEARCH_PROTOSSGROUNDARMORLEVEL3',
    'RESEARCH_PROTOSSGROUNDWEAPONS',
    'RESEARCH_PROTOSSGROUNDWEAPONSLEVEL1',
    'RESEARCH_PROTOSSGROUNDWEAPONSLEVEL2',
    'RESEARCH_PROTOSSGROUNDWEAPONSLEVEL3',
    'RESEARCH_PROTOSSSHIELDS',
    'RESEARCH_PROTOSSSHIELDSLEVEL1',
    'RESEARCH_PROTOSSSHIELDSLEVEL2',
    'RESEARCH_PROTOSSSHIELDSLEVEL3',
    'RESEARCH_PSISTORM',
    'RESEARCH_RAPIDFIRELAUNCHERS',
    'RESEARCH_SHADOWSTRIKE',
    'RESEARCH_WARPGATE',
    
    # Train
    'TRAIN_ADEPT',
    'TRAIN_CARRIER',
    'TRAIN_COLOSSUS',
    'TRAIN_DARKTEMPLAR',
    'TRAIN_DISRUPTOR',
    'TRAIN_HIGHTEMPLAR',
    'TRAIN_IMMORTAL',
    'TRAIN_MOTHERSHIP',
    'TRAIN_MOTHERSHIPCORE',
    'TRAIN_OBSERVER',
    'TRAIN_ORACLE',
    'TRAIN_PHOENIX',
    'TRAIN_PROBE',
    'TRAIN_SENTRY',
    'TRAIN_STALKER',
    'TRAIN_TEMPEST',
    'TRAIN_VOIDRAY',
    'TRAIN_WARPPRISM',
    'TRAIN_ZEALOT'
]

def train():
    pass

if __name__ == "__main__":
    pass