# Mapping of macro actions to output neurons
protoss_action_mapper = {
    # Build
    882: 0,    # BUILD_ASSIMILATOR
    894: 1,    # BUILD_CYBERNETICSCORE
    891: 2,    # BUILD_DARKSHRINE
    885: 3,    # BUILD_FLEETBEACON
    884: 4,    # BUILD_FORGE
    883: 5,    # BUILD_GATEWAY
    1042: 6,   # BUILD_INTERCEPTORS
    880: 7,    # BUILD_NEXUS
    887: 8,    # BUILD_PHOTONCANNON
    881: 9,    # BUILD_PYLON
    892: 10,   # BUILD_ROBOTICSBAY
    893: 11,   # BUILD_ROBOTICSFACILITY
    895: 12,   # BUILD_SHIELDBATTERY
    889: 13,   # BUILD_STARGATE
    2505: 14,  # BUILD_STASISTRAP
    890: 15,   # BUILD_TEMPLARARCHIVE
    886: 16,   # BUILD_TWILIGHTCOUNCIL

    # Morph
    1766: 17,  # MORPH_ARCHON
    1520: 18,  # MORPH_GATEWAY
    1847: 19,  # MORPH_MOTHERSHIP
    1518: 20,  # MORPH_WARPGATE

    # Research
    1594: 21,  # RESEARCH_ADEPTRESONATINGGLAIVES
    1593: 22,  # RESEARCH_BLINK
    1592: 23,  # RESEARCH_CHARGE
    1097: 24,  # RESEARCH_EXTENDEDTHERMALLANCE
    1093: 25,  # RESEARCH_GRAVITICBOOSTER
    1094: 26,  # RESEARCH_GRAVITICDRIVE
    44: 27,    # RESEARCH_INTERCEPTORGRAVITONCATAPULT
    766: 28,   # RESEARCH_MAGFIELDLAUNCHERS
    46: 29,    # RESEARCH_PHOENIXANIONPULSECRYSTALS
    1565: 30,  # RESEARCH_PROTOSSAIRARMORLEVEL1
    1566: 31,  # RESEARCH_PROTOSSAIRARMORLEVEL2
    1567: 32,  # RESEARCH_PROTOSSAIRARMORLEVEL3
    1562: 33,  # RESEARCH_PROTOSSAIRWEAPONSLEVEL1
    1563: 34,  # RESEARCH_PROTOSSAIRWEAPONSLEVEL2
    1564: 35,  # RESEARCH_PROTOSSAIRWEAPONSLEVEL3
    1065: 36,  # RESEARCH_PROTOSSGROUNDARMORLEVEL1
    1066: 37,  # RESEARCH_PROTOSSGROUNDARMORLEVEL2
    1067: 38,  # RESEARCH_PROTOSSGROUNDARMORLEVEL3
    1062: 39,  # RESEARCH_PROTOSSGROUNDWEAPONSLEVEL1
    1063: 40,  # RESEARCH_PROTOSSGROUNDWEAPONSLEVEL2
    1064: 41,  # RESEARCH_PROTOSSGROUNDWEAPONSLEVEL3
    1068: 42,  # RESEARCH_PROTOSSSHIELDSLEVEL1
    1069: 43,  # RESEARCH_PROTOSSSHIELDSLEVEL2
    1070: 44,  # RESEARCH_PROTOSSSHIELDSLEVEL3
    1126: 45,  # RESEARCH_PSISTORM
    2720: 46,  # RESEARCH_SHADOWSTRIKE
    1568: 47,  # RESEARCH_WARPGATE

    # Train
    922: 48,   # TRAIN_ADEPT
    948: 49,   # TRAIN_CARRIER
    978: 50,   # TRAIN_COLOSSUS
    920: 51,   # TRAIN_DARKTEMPLAR
    994: 52,   # TRAIN_DISRUPTOR
    919: 53,   # TRAIN_HIGHTEMPLAR
    979: 54,   # TRAIN_IMMORTAL
    110: 55,   # TRAIN_MOTHERSHIP
    1853: 56,  # TRAIN_MOTHERSHIPCORE
    977: 57,   # TRAIN_OBSERVER
    954: 58,   # TRAIN_ORACLE
    946: 59,   # TRAIN_PHOENIX
    1006: 60,  # TRAIN_PROBE
    921: 61,   # TRAIN_SENTRY
    917: 62,   # TRAIN_STALKER
    955: 63,   # TRAIN_TEMPEST
    950: 64,   # TRAIN_VOIDRAY
    976: 65,   # TRAIN_WARPPRISM
    916: 66,   # TRAIN_ZEALOT

    # TrainWarp
    1419: 48,  # TRAINWARP_ADEPT
    1417: 51,  # TRAINWARP_DARKTEMPLAR
    1416: 53,  # TRAINWARP_HIGHTEMPLAR
    1418: 61,  # TRAINWARP_SENTRY
    1414: 62,  # TRAINWARP_STALKER
    1413: 66,  # TRAINWARP_ZEALOT

    # # Cancel
    # 3659,  # CANCEL
    # 313,   # CANCELSLOT_ADDON
    # 305,   # CANCELSLOT_QUEUE1
    # 307,   # CANCELSLOT_QUEUE5
    # 309,   # CANCELSLOT_QUEUECANCELTOSELECTION
    # 1832,  # CANCELSLOT_QUEUEPASSIVE
    # 314,   # CANCEL_BUILDINPROGRESS
    # 3671,  # CANCEL_LAST
    # 1848,  # CANCEL_MORPHMOTHERSHIP
    # 304,   # CANCEL_QUEUE1
    # 306,   # CANCEL_QUEUE5
    # 312,   # CANCEL_QUEUEADDON
    # 308,   # CANCEL_QUEUECANCELTOSELECTION
    # 1831,  # CANCEL_QUEUEPASIVE
    # 1833,  # CANCEL_QUEUEPASSIVECANCELTOSELECTION

    # # Stop
    # 3665,  # STOP
    # 2057,  # STOP_BUILDING
    # 4,     # STOP_STOP
}

# The amount of different macro actions a player can take. 
protoss_macro_actions = [
    # Buildings
    'BUILD_ASSIMILATOR',
    'BUILD_CYBERNETICSCORE',
    'BUILD_DARKSHRINE',
    'BUILD_FLEETBEACON',
    'BUILD_FORGE',
    'BUILD_GATEWAY',
    'BUILD_INTERCEPTORS',
    'BUILD_NEXUS',
    'BUILD_PHOTONCANNON',
    'BUILD_PYLON',
    'BUILD_ROBOTICSBAY',
    'BUILD_ROBOTICSFACILITY',
    'BUILD_SHIELDBATTERY',
    'BUILD_STARGATE',
    'BUILD_STASISTRAP',
    'BUILD_TEMPLARARCHIVE',
    'BUILD_TWILIGHTCOUNCIL',

    # Morph
    'MORPH_ARCHON',
    'MORPH_GATEWAY',
    'MORPH_MOTHERSHIP',
    'MORPH_WARPGATE',

    # Research
    'RESEARCH_ADEPTRESONATINGGLAIVES',
    'RESEARCH_BLINK',
    'RESEARCH_CHARGE',
    'RESEARCH_EXTENDEDTHERMALLANCE',
    'RESEARCH_GRAVITICBOOSTER',
    'RESEARCH_GRAVITICDRIVE',
    'RESEARCH_INTERCEPTORGRAVITONCATAPULT',
    'RESEARCH_PHOENIXANIONPULSECRYSTALS',
    'RESEARCH_PROTOSSAIRARMOR',
    'RESEARCH_PROTOSSAIRARMORLEVEL1',
    'RESEARCH_PROTOSSAIRARMORLEVEL2',
    'RESEARCH_PROTOSSAIRARMORLEVEL3',
    'RESEARCH_PROTOSSAIRWEAPONS',
    'RESEARCH_PROTOSSAIRWEAPONSLEVEL1',
    'RESEARCH_PROTOSSAIRWEAPONSLEVEL2',
    'RESEARCH_PROTOSSAIRWEAPONSLEVEL3',
    'RESEARCH_PROTOSSGROUNDARMOR',
    'RESEARCH_PROTOSSGROUNDARMORLEVEL1',
    'RESEARCH_PROTOSSGROUNDARMORLEVEL2',
    'RESEARCH_PROTOSSGROUNDARMORLEVEL3',
    'RESEARCH_PROTOSSGROUNDWEAPONS',
    'RESEARCH_PROTOSSGROUNDWEAPONSLEVEL1',
    'RESEARCH_PROTOSSGROUNDWEAPONSLEVEL2',
    'RESEARCH_PROTOSSGROUNDWEAPONSLEVEL3',
    'RESEARCH_PROTOSSSHIELDS',
    'RESEARCH_PROTOSSSHIELDSLEVEL1',
    'RESEARCH_PROTOSSSHIELDSLEVEL2',
    'RESEARCH_PROTOSSSHIELDSLEVEL3',
    'RESEARCH_PSISTORM',
    'RESEARCH_RAPIDFIRELAUNCHERS',
    'RESEARCH_SHADOWSTRIKE',
    'RESEARCH_WARPGATE',
    
    # Train
    'TRAIN_ADEPT',
    'TRAIN_CARRIER',
    'TRAIN_COLOSSUS',
    'TRAIN_DARKTEMPLAR',
    'TRAIN_DISRUPTOR',
    'TRAIN_HIGHTEMPLAR',
    'TRAIN_IMMORTAL',
    'TRAIN_MOTHERSHIP',
    'TRAIN_MOTHERSHIPCORE',
    'TRAIN_OBSERVER',
    'TRAIN_ORACLE',
    'TRAIN_PHOENIX',
    'TRAIN_PROBE',
    'TRAIN_SENTRY',
    'TRAIN_STALKER',
    'TRAIN_TEMPEST',
    'TRAIN_VOIDRAY',
    'TRAIN_WARPPRISM',
    'TRAIN_ZEALOT'
]